### ISSUE TITLE
Build Process

### ISSUE THREAD

**Issue by clentfort** [thejameskyle/ast-pretty-print#1]
Hi, sorry for asking such a general question here, but since my Twitter-account is not confirmed on twitter you will probably not see my notifications there.

How is your development process in regards of flow-typing? To you directly type any annotation out as a comment or do you use "regular" flow-syntax and then use something like [babel-plugin-transform-flow-comments](https://www.npmjs.com/package/babel-plugin-transform-flow-comments) before you publish to GitHub?

Also: You forgot do disable issues, again. :O

**Comment by thejameskyle** [comment]
For small modules like this I just use the flow comment syntax cause I'm too lazy to setup a build process every time
